Performance enhancement

diff --git a/SOURCES/nagrestconf-1/scripts/nagctl b/SOURCES/nagrestconf-1/scripts/nagctl
--- a/SOURCES/nagrestconf-1/scripts/nagctl
+++ b/SOURCES/nagrestconf-1/scripts/nagctl
@@ -901,11 +901,14 @@ modify_hosttemplate_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    contacts=`echo "$gcsv" | cut -d, -f3`
-    contactgroups=`echo "$gcsv" | cut -d, -f4`
-    notifperiod=`echo "$gcsv" | cut -d, -f8`
-    checkperiod=`echo "$gcsv" | cut -d, -f11`
+    IFS=, read name x contacts contactgroups x x x notifperiod \
+        x x checkperiod < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #contacts=`echo "$gcsv" | cut -d, -f3`
+    #contactgroups=`echo "$gcsv" | cut -d, -f4`
+    #notifperiod=`echo "$gcsv" | cut -d, -f8`
+    #checkperiod=`echo "$gcsv" | cut -d, -f11`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -971,11 +974,14 @@ modify_servicetemplate_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    contacts=`echo "$gcsv" | cut -d, -f3`
-    contactgroups=`echo "$gcsv" | cut -d, -f4`
-    notifperiod=`echo "$gcsv" | cut -d, -f10`
-    checkperiod=`echo "$gcsv" | cut -d, -f12`
+    IFS=, read name x contacts contactgroups x x x x x notifperiod \
+        x checkperiod < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #contacts=`echo "$gcsv" | cut -d, -f3`
+    #contactgroups=`echo "$gcsv" | cut -d, -f4`
+    #notifperiod=`echo "$gcsv" | cut -d, -f10`
+    #checkperiod=`echo "$gcsv" | cut -d, -f12`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1041,12 +1047,14 @@ modify_host_line()
 {
     local name disabled a
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    template=`echo "$gcsv" | cut -d, -f4`
-    hostgroups=`echo "$gcsv" | cut -d, -f5`
-    contacts=`echo "$gcsv" | cut -d, -f6`
-    contactgroups=`echo "$gcsv" | cut -d, -f7`
-    disable=`echo "$gcsv" | cut -d, -f10`
+    IFS=, read name x x template hostgroups contacts contactgroups \
+        x x disable < <( echo "$gcsv" )
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #template=`echo "$gcsv" | cut -d, -f4`
+    #hostgroups=`echo "$gcsv" | cut -d, -f5`
+    #contacts=`echo "$gcsv" | cut -d, -f6`
+    #contactgroups=`echo "$gcsv" | cut -d, -f7`
+    #disable=`echo "$gcsv" | cut -d, -f10`
 
     lockdir
     if ! item_exists 1 $FILE_HOSTS "$name"; then
@@ -1125,14 +1133,20 @@ modify_service_line()
 {
     local name svcdesc
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    template=`echo "$gcsv" | cut -d, -f2`
-    command=`echo "$gcsv" | cut -d, -f3 | grep -o '[-A-Za-z0-9_+]*'`
-    svcdesc=`echo "$gcsv" | cut -d, -f4`
-    servicegroups=`echo "$gcsv" | cut -d, -f5`
-    contacts=`echo "$gcsv" | cut -d, -f6`
-    contactgroups=`echo "$gcsv" | cut -d, -f7`
-    disable=`echo "$gcsv" | cut -d, -f11`
+    IFS=, read name template command svcdesc servicegroups \
+        contacts contactgroups x x x disable < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #template=`echo "$gcsv" | cut -d, -f2`
+
+    command=`echo "$command" | grep -o '[-A-Za-z0-9_+]*'`
+
+    #command=`echo "$gcsv" | cut -d, -f3 | grep -o '[-A-Za-z0-9_+]*'`
+    #svcdesc=`echo "$gcsv" | cut -d, -f4`
+    #servicegroups=`echo "$gcsv" | cut -d, -f5`
+    #contacts=`echo "$gcsv" | cut -d, -f6`
+    #contactgroups=`echo "$gcsv" | cut -d, -f7`
+    #disable=`echo "$gcsv" | cut -d, -f11`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1226,7 +1240,9 @@ modify_hostgroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1255,7 +1271,9 @@ modify_servicegroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1284,9 +1302,11 @@ modify_contacts_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    svcnp=`echo "$gcsv" | cut -d, -f5`
-    hstnp=`echo "$gcsv" | cut -d, -f8`
+    IFS=, read name x x x svcnp x x hstnp < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #svcnp=`echo "$gcsv" | cut -d, -f5`
+    #hstnp=`echo "$gcsv" | cut -d, -f8`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1330,8 +1350,10 @@ modify_contactgroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    memberlist=`echo "$gcsv" | cut -d, -f3`
+    IFS=, read name x memberlist < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #memberlist=`echo "$gcsv" | cut -d, -f3`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1369,12 +1391,15 @@ modify_servicesets_line()
 {
     local name svcdesc
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    template=`echo "$gcsv" | cut -d, -f2`
-    svcdesc=`echo "$gcsv" | cut -d, -f4`
-    servicegroups=`echo "$gcsv" | cut -d, -f5`
-    contacts=`echo "$gcsv" | cut -d, -f6`
-    contactgroups=`echo "$gcsv" | cut -d, -f7`
+    IFS=, read name template x svcdesc servicegroups contacts \
+        contactgroups < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #template=`echo "$gcsv" | cut -d, -f2`
+    #svcdesc=`echo "$gcsv" | cut -d, -f4`
+    #servicegroups=`echo "$gcsv" | cut -d, -f5`
+    #contacts=`echo "$gcsv" | cut -d, -f6`
+    #contactgroups=`echo "$gcsv" | cut -d, -f7`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1446,8 +1471,10 @@ modify_timeperiods_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    exclude=`echo "$gcsv" | cut -d, -f4`
+    IFS=, read name x x exclude < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #exclude=`echo "$gcsv" | cut -d, -f4`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1488,7 +1515,9 @@ modify_commands_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1527,11 +1556,14 @@ add_hosttemplate_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    contacts=`echo "$gcsv" | cut -d, -f3`
-    contactgroups=`echo "$gcsv" | cut -d, -f4`
-    notifperiod=`echo "$gcsv" | cut -d, -f8`
-    checkperiod=`echo "$gcsv" | cut -d, -f11`
+    IFS=, read name x contacts contactgroups x x x notifperiod \
+        x x checkperiod < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #contacts=`echo "$gcsv" | cut -d, -f3`
+    #contactgroups=`echo "$gcsv" | cut -d, -f4`
+    #notifperiod=`echo "$gcsv" | cut -d, -f8`
+    #checkperiod=`echo "$gcsv" | cut -d, -f11`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1593,11 +1625,14 @@ add_servicetemplate_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    contacts=`echo "$gcsv" | cut -d, -f3`
-    contactgroups=`echo "$gcsv" | cut -d, -f4`
-    notifperiod=`echo "$gcsv" | cut -d, -f10`
-    checkperiod=`echo "$gcsv" | cut -d, -f12`
+    IFS=, read name x contacts contactgroups x x x x x notifperiod \
+        x checkperiod < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #contacts=`echo "$gcsv" | cut -d, -f3`
+    #contactgroups=`echo "$gcsv" | cut -d, -f4`
+    #notifperiod=`echo "$gcsv" | cut -d, -f10`
+    #checkperiod=`echo "$gcsv" | cut -d, -f12`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1659,12 +1694,15 @@ add_host_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    template=`echo "$gcsv" | cut -d, -f4`
-    hostgroups=`echo "$gcsv" | cut -d, -f5`
-    contacts=`echo "$gcsv" | cut -d, -f6`
-    contactgroups=`echo "$gcsv" | cut -d, -f7`
-    servicesets=`echo "$gcsv" | cut -d, -f9`
+    IFS=, read name x x template hostgroups contacts contactgroups \
+        x servicesets < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #template=`echo "$gcsv" | cut -d, -f4`
+    #hostgroups=`echo "$gcsv" | cut -d, -f5`
+    #contacts=`echo "$gcsv" | cut -d, -f6`
+    #contactgroups=`echo "$gcsv" | cut -d, -f7`
+    #servicesets=`echo "$gcsv" | cut -d, -f9`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1749,13 +1787,19 @@ add_service_line()
 {
     local name svcdesc
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    template=`echo "$gcsv" | cut -d, -f2`
-    command=`echo "$gcsv" | cut -d, -f3 | grep -o '[-A-Za-z0-9_+]*'`
-    svcdesc=`echo "$gcsv" | cut -d, -f4`
-    servicegroups=`echo "$gcsv" | cut -d, -f5`
-    contacts=`echo "$gcsv" | cut -d, -f6`
-    contactgroups=`echo "$gcsv" | cut -d, -f7`
+    IFS=, read name template command svcdesc servicegroups \
+        contacts contactgroups < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #template=`echo "$gcsv" | cut -d, -f2`
+
+    command=`echo "$command" | grep -o '[-A-Za-z0-9_+]*'`
+
+    #command=`echo "$gcsv" | cut -d, -f3 | grep -o '[-A-Za-z0-9_+]*'`
+    #svcdesc=`echo "$gcsv" | cut -d, -f4`
+    #servicegroups=`echo "$gcsv" | cut -d, -f5`
+    #contacts=`echo "$gcsv" | cut -d, -f6`
+    #contactgroups=`echo "$gcsv" | cut -d, -f7`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1837,7 +1881,9 @@ add_hostgroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1863,7 +1909,9 @@ add_servicegroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1889,9 +1937,11 @@ add_contacts_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    svcnp=`echo "$gcsv" | cut -d, -f5`
-    hstnp=`echo "$gcsv" | cut -d, -f8`
+    IFS=, read name x x x svcnp x x hstnp < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #svcnp=`echo "$gcsv" | cut -d, -f5`
+    #hstnp=`echo "$gcsv" | cut -d, -f8`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1932,8 +1982,10 @@ add_contactgroups_line()
 {
     local name i
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    memberlist=`echo "$gcsv" | cut -d, -f3`
+    IFS=, read name x memberlist < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #memberlist=`echo "$gcsv" | cut -d, -f3`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -1967,14 +2019,20 @@ add_servicesets_line()
 {
     local name svcdesc
 
+    IFS=, read name template command svcdesc servicegroups contacts \
+        contactgroups < <( echo "$gcsv" )
+
     # Same name and svcdesc is an error (duplicate)
-    name=`echo "$gcsv" | cut -d, -f1`
-    template=`echo "$gcsv" | cut -d, -f2`
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #template=`echo "$gcsv" | cut -d, -f2`
+
     command=`echo "$gcsv" | cut -d, -f3 | grep -o '[-A-Za-z0-9_+]*'`
-    svcdesc=`echo "$gcsv" | cut -d, -f4`
-    servicegroups=`echo "$gcsv" | cut -d, -f5`
-    contacts=`echo "$gcsv" | cut -d, -f6`
-    contactgroups=`echo "$gcsv" | cut -d, -f7`
+
+    #command=`echo "$gcsv" | cut -d, -f3 | grep -o '[-A-Za-z0-9_+]*'`
+    #svcdesc=`echo "$gcsv" | cut -d, -f4`
+    #servicegroups=`echo "$gcsv" | cut -d, -f5`
+    #contacts=`echo "$gcsv" | cut -d, -f6`
+    #contactgroups=`echo "$gcsv" | cut -d, -f7`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2049,8 +2107,10 @@ add_timeperiods_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    exclude=`echo "$gcsv" | cut -d, -f4`
+    IFS=, read name x x exclude < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #exclude=`echo "$gcsv" | cut -d, -f4`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2086,7 +2146,9 @@ add_commands_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2105,6 +2167,78 @@ add_commands_line()
 
     echo "Success"
     exit 0
+}
+
+# ----------------------------------------------------------------------------
+add_hosttemplate_line()
+# ----------------------------------------------------------------------------
+# Purpose:      Add a line to the hosttemplates file.
+# Arguments:    None
+# Returns:      Nothing
+{
+    local name
+
+    IFS=, read name x contacts contactgroups x x x notifperiod \
+        x x checkperiod < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #contacts=`echo "$gcsv" | cut -d, -f3`
+    #contactgroups=`echo "$gcsv" | cut -d, -f4`
+    #notifperiod=`echo "$gcsv" | cut -d, -f8`
+    #checkperiod=`echo "$gcsv" | cut -d, -f11`
+
+    [[ $name == *" "* ]] && {
+        echo "NAGCTL ERROR: 'name' field cannot contain spaces"
+        exit 13
+    }
+
+    lockdir
+    if item_exists 1 $FILE_HOSTTEMPLATES "$name"; then
+        echo "NAGCTL ERROR: Host template name is a duplicate. Cannot add item."
+        unlockdir
+        exit 13
+    fi
+
+    if ! item_exists 1 $FILE_TIMEPERIODS $notifperiod; then
+        echo -n "NAGCTL ERROR: Notifperiod '$notifperiod' unavailable."
+        echo "Will not add host template."
+        unlockdir
+        exit 14
+    fi
+
+    if ! item_exists 1 $FILE_TIMEPERIODS $checkperiod; then
+        echo -n "NAGCTL ERROR: Checkperiod '$checkperiod' unavailable."
+        echo "Will not add host template."
+        unlockdir
+        exit 14
+    fi
+
+    [[ -n $contacts  && $contacts != "-" ]] && {
+        for i in $contacts; do
+            if ! item_exists 1 $FILE_CONTACTS "$i"; then
+                echo -n "NAGCTL ERROR: Contact '$i' not found."
+                echo " Will not add host template."
+                unlockdir
+                exit 13
+            fi
+        done
+    }
+
+    [[ -n $contactgroups  && $contactgroups != "-" ]] && {
+        for i in $contactgroups; do
+            if ! item_exists 1 $FILE_CONTACTGROUPS "$i"; then
+                echo "NAGCTL ERROR: Contact Group '$i' not found."
+                echo " Will not add host template."
+                unlockdir
+                exit 13
+            fi
+        done
+    }
+
+    echo "$gcsv" >>$SETUP_FILE
+    unlockdir
+
+    echo "Success"
 }
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -2247,7 +2381,9 @@ delete_hosttemplate_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2277,7 +2413,9 @@ delete_servicetemplate_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2307,7 +2445,9 @@ delete_host_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2337,8 +2477,10 @@ delete_service_line()
 {
     local name svcdesc
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    svcdesc=`echo "$gcsv" | cut -d, -f4`
+    IFS=, read name x x svcdesc < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #svcdesc=`echo "$gcsv" | cut -d, -f4`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2362,7 +2504,9 @@ delete_hostgroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2392,7 +2536,9 @@ delete_servicegroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2422,7 +2568,9 @@ delete_contacts_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2468,7 +2616,9 @@ delete_contactgroups_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2510,8 +2660,10 @@ delete_servicesets_line()
 {
     local name svcdesc
 
-    name=`echo "$gcsv" | cut -d, -f1`
-    svcdesc=`echo "$gcsv" | cut -d, -f4`
+    IFS=, read name x x svcdesc < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
+    #svcdesc=`echo "$gcsv" | cut -d, -f4`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2535,7 +2687,9 @@ delete_timeperiods_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
@@ -2589,7 +2743,9 @@ delete_commands_line()
 {
     local name
 
-    name=`echo "$gcsv" | cut -d, -f1`
+    IFS=, read name < <( echo "$gcsv" )
+
+    #name=`echo "$gcsv" | cut -d, -f1`
 
     [[ $name == *" "* ]] && {
         echo "NAGCTL ERROR: 'name' field cannot contain spaces"
